version: '3.4'

services:
  api:
    image: budgetfriend
    container_name: budgetfriend-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: pipenv run python -m uvicorn app:api --host 0.0.0.0 --reload
    ports:
      - "8005:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    environment:
      MONGODB_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo/"
  mongo:
    image: mongo:latest
    container_name: budgetfriend-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
  postgres:
    image: postgres
    container_name: budgetfriend-pg
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    command: postgres -c listen_addresses="*"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: budgetfriend-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${DEVELOPER_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_DB}"
    ports:
      - "4321:80"
